language: bash 
services:
  - docker

script: docker run --rm -v $(pwd):/app -w /app/test thrustjs/thrust-docker:0.5.3 /bin/sh -c "chmod +x test.sh && test.sh"

deploy:
  provider: releases
  api_key: $githubToken
  skip_cleanup: true
  on:
    tags: true
